//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
module table {
	/**
	 * FILE: 多语言.xlsx SHEET: 多语言 KEY: id
	 */
	export class TableLanguage {
		/**
		 * 序号
		 */
		id: number;
		/**
		 * 英文
		 */
		en: string;
		/**
		 * 印尼语
		 */
		in: string;

		GetType(): string { return 'table.TableLanguage'; }
	}
}
