var __reflect = (this && this.__reflect) || function (p, c, t) {
    p.__class__ = c, t ? t.push(c) : t = [c], p.__types__ = p.__types__ ? t.concat(p.__types__) : t;
};
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
var table;
(function (table) {
    /**
     * FILE: 多语言.xlsx SHEET: 多语言 KEY: id
     */
    var TableLanguage = (function () {
        function TableLanguage() {
        }
        TableLanguage.prototype.GetType = function () { return 'table.TableLanguage'; };
        return TableLanguage;
    }());
    table.TableLanguage = TableLanguage;
    __reflect(TableLanguage.prototype, "table.TableLanguage");
})(table || (table = {}));
